<?php

namespace ContainerOkjyALH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3axGDdmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3axGDdm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', false],
        ], [
            'security' => '?',
        ]);

        if (isset($container->privates['.service_locator.3axGDdm'])) {
            return $container->privates['.service_locator.3axGDdm'];
        }

        return $container->privates['.service_locator.3axGDdm'] = $instance;
    }
}
