<?php

namespace ContainerOkjyALH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresasControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\v1\EmpresasController' autowired service.
     *
     * @return \App\Controller\v1\EmpresasController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'v1'.\DIRECTORY_SEPARATOR.'EmpresasController.php';

        $container->factories['App\\Controller\\v1\\EmpresasController'] = function ($container) {
            $instance = new \App\Controller\v1\EmpresasController(($container->privates['App\\Service\\EmpresasService'] ?? $container->load('getEmpresasServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalCompanySyncService'] ?? $container->load('getFiscalCompanySyncServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Controller\\v1\\EmpresasController'] ?? $container->load('getEmpresasController2Service')));

            return $instance;
        };

        return $container->factories['App\\Controller\\v1\\EmpresasController']($container);
    }
}
