<?php

namespace ContainerOkjyALH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalEmailProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalEmailProcessor' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalEmailProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalEmailProcessor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalMailerService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalFileFetcher.php';

        $a = ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'];
        }

        $instance = new \App\Service\Fiscal\FiscalEmailProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), $a, new \App\Service\Fiscal\FiscalMailerService(new \Symfony\Component\Mailer\Mailer(($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService')), NULL, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container))), ($container->privates['App\\Service\\Fiscal\\FiscalFileFetcher'] ??= new \App\Service\Fiscal\FiscalFileFetcher((\dirname(__DIR__, 4).'/var/fiscal_storage'))), $container->getEnv('default::FISCAL_MAIL_FROM'), $container->getEnv('default::FISCAL_MAIL_FROM_NAME')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $container->getEnv('default::FISCAL_MAIL_FROM'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'];
        }

        return $container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'] = $instance;
    }
}
