<?php

namespace ContainerOkjyALH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalAlertServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Observability\FiscalAlertService' shared autowired service.
     *
     * @return \App\Service\Fiscal\Observability\FiscalAlertService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Observability'.\DIRECTORY_SEPARATOR.'FiscalAlertService.php';

        return $container->privates['App\\Service\\Fiscal\\Observability\\FiscalAlertService'] = new \App\Service\Fiscal\Observability\FiscalAlertService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\FiscalAlertRepository'] ?? $container->load('getFiscalAlertRepositoryService')), ($container->privates['App\\Repository\\FiscalAuditLogRepository'] ?? $container->load('getFiscalAuditLogRepositoryService')), ($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService')));
    }
}
