<?php

namespace ContainerOkjyALH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalEmitProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalEmitProcessor' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalEmitProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalEmitProcessor.php';

        $a = ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'];
        }
        $b = ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'] ?? $container->load('getFiscalAuditServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'];
        }

        $instance = new \App\Service\Fiscal\FiscalEmitProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), ($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')), ($container->privates['App\\Service\\Fiscal\\FiscalStorageService'] ?? $container->load('getFiscalStorageServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalWebhookService'] ?? $container->load('getFiscalWebhookServiceService')), $a, ($container->privates['App\\Service\\Fiscal\\Provider\\FiscalProviderResolver'] ?? $container->load('getFiscalProviderResolverService')), ($container->privates['App\\Service\\Fiscal\\FiscalPdfService'] ?? $container->load('getFiscalPdfServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $b, ($container->privates['App\\Service\\Fiscal\\FiscalDocumentPdfResolver'] ?? $container->load('getFiscalDocumentPdfResolverService')));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'];
        }

        return $container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'] = $instance;
    }
}
