<?php

namespace ContainerOkjyALH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\v1\FiscalController' autowired service.
     *
     * @return \App\Controller\v1\FiscalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'v1'.\DIRECTORY_SEPARATOR.'FiscalController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalFileFetcher.php';

        $container->factories['App\\Controller\\v1\\FiscalController'] = function ($container) {
            $instance = new \App\Controller\v1\FiscalController(($container->privates['App\\Service\\Fiscal\\FiscalDocumentService'] ?? $container->load('getFiscalDocumentServiceService')), ($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), ($container->privates['App\\Service\\Fiscal\\FiscalDocumentDetailService'] ?? $container->load('getFiscalDocumentDetailServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalFileFetcher'] ??= new \App\Service\Fiscal\FiscalFileFetcher((\dirname(__DIR__, 4).'/var/fiscal_storage'))), ($container->privates['App\\Service\\Fiscal\\FiscalBulkActionService'] ?? $container->load('getFiscalBulkActionServiceService')), ($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->privates['App\\Service\\Fiscal\\FiscalCompanySyncService'] ?? $container->load('getFiscalCompanySyncServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalConnectionTestService'] ?? $container->load('getFiscalConnectionTestServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalDocumentPdfResolver'] ?? $container->load('getFiscalDocumentPdfResolverService')));

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Controller\\v1\\FiscalController'] ?? $container->load('getFiscalController2Service')));

            return $instance;
        };

        return $container->factories['App\\Controller\\v1\\FiscalController']($container);
    }
}
