<?php

namespace ContainerOkjyALH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Greenter\See' shared autowired service.
     *
     * @return \Greenter\See
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'lite'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Greenter'.\DIRECTORY_SEPARATOR.'See.php';

        $container->services['Greenter\\See'] = $instance = new \Greenter\See();

        $instance->setCachePath($container->targetDir.'');

        return $instance;
    }
}
