<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QVGEahrService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.QVGEahr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AccountController::changePassword' => ['privates', '.service_locator.kT20yG8.App\\Controller\\AccountController::changePassword()', 'getAccountControllerchangePasswordService', true],
            'App\\Controller\\FiscalDashboardController::index' => ['privates', '.service_locator.3axGDdm.App\\Controller\\FiscalDashboardController::index()', 'getFiscalDashboardControllerindexService', true],
            'App\\Controller\\FiscalEmpresasController::index' => ['privates', '.service_locator.3axGDdm.App\\Controller\\FiscalEmpresasController::index()', 'getFiscalEmpresasControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UjD30F4.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\v1\\DespatchController::send' => ['privates', '.service_locator.wsaarWP.App\\Controller\\v1\\DespatchController::send()', 'getDespatchControllersendService', true],
            'App\\Controller\\v1\\DespatchController::status' => ['privates', '.service_locator.wsaarWP.App\\Controller\\v1\\DespatchController::status()', 'getDespatchControllerstatusService', true],
            'App\\Controller\\v1\\ReversionController::status' => ['privates', '.service_locator.CkeVmBk.App\\Controller\\v1\\ReversionController::status()', 'getReversionControllerstatusService', true],
            'App\\Controller\\v1\\SummaryController::status' => ['privates', '.service_locator.CkeVmBk.App\\Controller\\v1\\SummaryController::status()', 'getSummaryControllerstatusService', true],
            'App\\Controller\\v1\\VoidedController::status' => ['privates', '.service_locator.CkeVmBk.App\\Controller\\v1\\VoidedController::status()', 'getVoidedControllerstatusService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AccountController:changePassword' => ['privates', '.service_locator.kT20yG8.App\\Controller\\AccountController::changePassword()', 'getAccountControllerchangePasswordService', true],
            'App\\Controller\\FiscalDashboardController:index' => ['privates', '.service_locator.3axGDdm.App\\Controller\\FiscalDashboardController::index()', 'getFiscalDashboardControllerindexService', true],
            'App\\Controller\\FiscalEmpresasController:index' => ['privates', '.service_locator.3axGDdm.App\\Controller\\FiscalEmpresasController::index()', 'getFiscalEmpresasControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UjD30F4.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\v1\\DespatchController:send' => ['privates', '.service_locator.wsaarWP.App\\Controller\\v1\\DespatchController::send()', 'getDespatchControllersendService', true],
            'App\\Controller\\v1\\DespatchController:status' => ['privates', '.service_locator.wsaarWP.App\\Controller\\v1\\DespatchController::status()', 'getDespatchControllerstatusService', true],
            'App\\Controller\\v1\\ReversionController:status' => ['privates', '.service_locator.CkeVmBk.App\\Controller\\v1\\ReversionController::status()', 'getReversionControllerstatusService', true],
            'App\\Controller\\v1\\SummaryController:status' => ['privates', '.service_locator.CkeVmBk.App\\Controller\\v1\\SummaryController::status()', 'getSummaryControllerstatusService', true],
            'App\\Controller\\v1\\VoidedController:status' => ['privates', '.service_locator.CkeVmBk.App\\Controller\\v1\\VoidedController::status()', 'getVoidedControllerstatusService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AccountController::changePassword' => '?',
            'App\\Controller\\FiscalDashboardController::index' => '?',
            'App\\Controller\\FiscalEmpresasController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\v1\\DespatchController::send' => '?',
            'App\\Controller\\v1\\DespatchController::status' => '?',
            'App\\Controller\\v1\\ReversionController::status' => '?',
            'App\\Controller\\v1\\SummaryController::status' => '?',
            'App\\Controller\\v1\\VoidedController::status' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AccountController:changePassword' => '?',
            'App\\Controller\\FiscalDashboardController:index' => '?',
            'App\\Controller\\FiscalEmpresasController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\v1\\DespatchController:send' => '?',
            'App\\Controller\\v1\\DespatchController:status' => '?',
            'App\\Controller\\v1\\ReversionController:status' => '?',
            'App\\Controller\\v1\\SummaryController:status' => '?',
            'App\\Controller\\v1\\VoidedController:status' => '?',
        ]);

        if (isset($container->privates['.service_locator.QVGEahr'])) {
            return $container->privates['.service_locator.QVGEahr'];
        }

        return $container->privates['.service_locator.QVGEahr'] = $instance;
    }
}
