<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\v1\ConfigurationController' autowired service.
     *
     * @return \App\Controller\v1\ConfigurationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'v1'.\DIRECTORY_SEPARATOR.'ConfigurationController.php';

        $container->factories['App\\Controller\\v1\\ConfigurationController'] = function ($container) {
            $instance = new \App\Controller\v1\ConfigurationController(($container->services['App\\Service\\ConfigProviderInterface'] ?? $container->load('getConfigProviderInterfaceService')), ($container->privates['App\\Service\\EmpresasService'] ?? $container->load('getEmpresasServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Controller\\v1\\ConfigurationController'] ?? $container->load('getConfigurationController2Service')));

            return $instance;
        };

        return $container->factories['App\\Controller\\v1\\ConfigurationController']($container);
    }
}
