<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentRequestParserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\DocumentRequestParser' shared autowired service.
     *
     * @return \App\Service\DocumentRequestParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RequestParserInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DocumentRequestParser.php';

        return $container->privates['App\\Service\\DocumentRequestParser'] = new \App\Service\DocumentRequestParser(($container->services['serializer'] ?? $container->load('getSerializerService')));
    }
}
