<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalDocumentPdfResolverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalDocumentPdfResolver' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalDocumentPdfResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalDocumentPdfResolver.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalFileFetcher.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalDocumentPdfResolver'] = new \App\Service\Fiscal\FiscalDocumentPdfResolver(($container->privates['App\\Service\\Fiscal\\FiscalFileFetcher'] ??= new \App\Service\Fiscal\FiscalFileFetcher((\dirname(__DIR__, 4).'/var/fiscal_storage'))), ($container->privates['App\\Service\\Fiscal\\FiscalPdfService'] ?? $container->load('getFiscalPdfServiceService')), ($container->services['serializer'] ?? $container->load('getSerializerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), (\dirname(__DIR__, 4).'/var/fiscal_storage'));
    }
}
