<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalWorkerCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\FiscalWorkerCommand' shared autowired service.
     *
     * @return \App\Command\FiscalWorkerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'FiscalWorkerCommand.php';

        $container->privates['App\\Command\\FiscalWorkerCommand'] = $instance = new \App\Command\FiscalWorkerCommand(($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'] ?? $container->load('getFiscalEmitProcessorService')), ($container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'] ?? $container->load('getFiscalEmailProcessorService')), ($container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'] ?? $container->load('getFiscalWebhookSyncProcessorService')), ($container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'] ?? $container->load('getFiscalStatusPollProcessorService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'] ?? $container->load('getFiscalAuditServiceService')));

        $instance->setName('app:fiscal:worker');

        return $instance;
    }
}
