<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalBulkActionServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalBulkActionService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalBulkActionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalBulkActionService.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalBulkActionService'] = new \App\Service\Fiscal\FiscalBulkActionService(($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService')));
    }
}
