<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalWebhookServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalWebhookService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalWebhookService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalWebhookService.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalWebhookService'] = new \App\Service\Fiscal\FiscalWebhookService($container->getEnv('default::ERP_WEBHOOK_URL'), $container->getEnv('default::ERP_WEBHOOK_KEY'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
