<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlReportService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Greenter\Report\HtmlReport' shared autowired service.
     *
     * @return \Greenter\Report\HtmlReport
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'ReportInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'HtmlReport.php';

        return $container->privates['Greenter\\Report\\HtmlReport'] = new \Greenter\Report\HtmlReport($container->getEnv('default::TEMPLATESPDF_PATH'), ['cache' => $container->targetDir.'', 'strict_variables' => true]);
    }
}
