<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\v1\InvoiceController' autowired service.
     *
     * @return \App\Controller\v1\InvoiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'v1'.\DIRECTORY_SEPARATOR.'InvoiceController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ConfigProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EnvConfigProvider.php';

        $container->factories['App\\Controller\\v1\\InvoiceController'] = function ($container) {
            $instance = new \App\Controller\v1\InvoiceController(($container->privates['App\\Service\\DocumentRequest'] ?? $container->load('getDocumentRequestService')), ($container->privates['App\\Service\\EnvConfigProvider'] ??= new \App\Service\EnvConfigProvider()), ($container->services['App\\Service\\ConfigProviderInterface'] ?? $container->load('getConfigProviderInterfaceService')), ($container->services['serializer'] ?? $container->load('getSerializerService')));

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Controller\\v1\\InvoiceController'] ?? $container->load('getInvoiceController2Service')));

            return $instance;
        };

        return $container->factories['App\\Controller\\v1\\InvoiceController']($container);
    }
}
