<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSunatDirectProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Provider\SunatDirectProvider' shared autowired service.
     *
     * @return \App\Service\Fiscal\Provider\SunatDirectProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'FiscalProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'AbstractFiscalProvider.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'SunatDirectProvider.php';

        return $container->privates['App\\Service\\Fiscal\\Provider\\SunatDirectProvider'] = new \App\Service\Fiscal\Provider\SunatDirectProvider(($container->services['App\\Service\\SeeFactory'] ?? $container->load('getSeeFactoryService')), (\dirname(__DIR__, 4).'/data'));
    }
}
