<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStorageDriverInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Storage\StorageDriverInterface' shared autowired service.
     *
     * @return \App\Service\Fiscal\Storage\StorageDriverInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Storage'.\DIRECTORY_SEPARATOR.'StorageDriverInterface.php';

        return $container->privates['App\\Service\\Fiscal\\Storage\\StorageDriverInterface'] = ($container->privates['App\\Service\\Fiscal\\Storage\\StorageDriverFactory'] ?? $container->load('getStorageDriverFactoryService'))->create();
    }
}
