<?php

namespace ContainerJm3YUER;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateResolverInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Greenter\Report\Resolver\TemplateResolverInterface' shared autowired service.
     *
     * @return \Greenter\Report\Resolver\DefaultTemplateResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'TemplateResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'DefaultTemplateResolver.php';

        return $container->services['Greenter\\Report\\Resolver\\TemplateResolverInterface'] = new \Greenter\Report\Resolver\DefaultTemplateResolver();
    }
}
