<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentRequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\DocumentRequest' shared autowired service.
     *
     * @return \App\Service\DocumentRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DocumentRequestInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DocumentRequest.php';

        return $container->privates['App\\Service\\DocumentRequest'] = new \App\Service\DocumentRequest(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Service\\DocumentRequestParser'] ?? $container->load('getDocumentRequestParserService')), $container);
    }
}
