<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDespatchControllerstatusService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.wsaarWP.App\Controller\v1\DespatchController::status()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wsaarWP.App\\Controller\\v1\\DespatchController::status()'] = ($container->privates['.service_locator.wsaarWP'] ?? $container->load('get_ServiceLocator_WsaarWPService'))->withContext('App\\Controller\\v1\\DespatchController::status()', $container);
    }
}
