<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalEmailProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalEmailProcessor' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalEmailProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalEmailProcessor.php';

        $a = ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'];
        }

        $instance = new \App\Service\Fiscal\FiscalEmailProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), $a, ($container->privates['App\\Service\\Fiscal\\FiscalMailerService'] ?? $container->load('getFiscalMailerServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $container->getEnv('default::FISCAL_MAIL_FROM'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'];
        }

        return $container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'] = $instance;
    }
}
