<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileDataReaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\FileDataReader' shared autowired service.
     *
     * @return \App\Service\FileDataReader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FileDataReader.php';

        return $container->services['App\\Service\\FileDataReader'] = new \App\Service\FileDataReader((\dirname(__DIR__, 4).'/data'));
    }
}
