<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalDocumentDetailServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalDocumentDetailService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalDocumentDetailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalDocumentDetailService.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalDocumentDetailService'] = new \App\Service\Fiscal\FiscalDocumentDetailService(($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), ($container->privates['App\\Repository\\FiscalEmitAttemptRepository'] ?? $container->load('getFiscalEmitAttemptRepositoryService')), ($container->privates['App\\Repository\\OutboundEmailLogRepository'] ?? $container->load('getOutboundEmailLogRepositoryService')), ($container->privates['App\\Repository\\FiscalWebhookEventRepository'] ?? $container->load('getFiscalWebhookEventRepositoryService')), ($container->privates['App\\Repository\\FiscalAuditLogRepository'] ?? $container->load('getFiscalAuditLogRepositoryService')), ($container->privates['App\\Service\\Fiscal\\FiscalDocumentPdfResolver'] ?? $container->load('getFiscalDocumentPdfResolverService')));
    }
}
