<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalWebhookSyncProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalWebhookSyncProcessor' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalWebhookSyncProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalWebhookSyncProcessor.php';

        $a = ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'];
        }

        $instance = new \App\Service\Fiscal\FiscalWebhookSyncProcessor(($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), ($container->privates['App\\Service\\Fiscal\\FiscalWebhookService'] ?? $container->load('getFiscalWebhookServiceService')), $a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'];
        }

        return $container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'] = $instance;
    }
}
