<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalOperationsServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Observability\FiscalOperationsService' shared autowired service.
     *
     * @return \App\Service\Fiscal\Observability\FiscalOperationsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Observability'.\DIRECTORY_SEPARATOR.'FiscalOperationsService.php';

        return $container->privates['App\\Service\\Fiscal\\Observability\\FiscalOperationsService'] = new \App\Service\Fiscal\Observability\FiscalOperationsService(($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), ($container->privates['App\\Repository\\FiscalAuditLogRepository'] ?? $container->load('getFiscalAuditLogRepositoryService')), ($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->privates['App\\Service\\Fiscal\\FiscalDocumentDetailService'] ?? $container->load('getFiscalDocumentDetailServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAlertService'] ?? $container->load('getFiscalAlertServiceService')));
    }
}
