<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalStorageServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalStorageService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalStorageService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalStorageService.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalStorageService'] = new \App\Service\Fiscal\FiscalStorageService(($container->privates['App\\Service\\Fiscal\\Storage\\StorageDriverInterface'] ?? $container->load('getStorageDriverInterfaceService')));
    }
}
