<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalQueueServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalQueueService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalQueueService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalQueueService.php';

        $instance = new \App\Service\Fiscal\FiscalQueueService($container->getEnv('default::REDIS_URL'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalQueueService'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalQueueService'];
        }

        $container->privates['App\\Service\\Fiscal\\FiscalQueueService'] = $instance;

        $instance->setJobDispatcher(($container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'] ?? $container->load('getFiscalJobDispatcherService')));

        return $instance;
    }
}
