<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalAuditServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Observability\FiscalAuditService' shared autowired service.
     *
     * @return \App\Service\Fiscal\Observability\FiscalAuditService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Observability'.\DIRECTORY_SEPARATOR.'FiscalAuditService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Observability'.\DIRECTORY_SEPARATOR.'FiscalSecretRedactor.php';

        $a = ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'])) {
            return $container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'];
        }

        $instance = new \App\Service\Fiscal\Observability\FiscalAuditService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalStructuredLogger'] ?? $container->load('getFiscalStructuredLoggerService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalSecretRedactor'] ??= new \App\Service\Fiscal\Observability\FiscalSecretRedactor()), $a, ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalMetricsService'] ?? $container->load('getFiscalMetricsServiceService')));

        if (isset($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'])) {
            return $container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'];
        }

        return $container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'] = $instance;
    }
}
