<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalJobDispatcherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalJobDispatcher' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalJobDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalJobDispatcher.php';

        $a = ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'];
        }
        $b = ($container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'] ?? $container->load('getFiscalEmitProcessorService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'];
        }
        $c = ($container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'] ?? $container->load('getFiscalEmailProcessorService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'];
        }
        $d = ($container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'] ?? $container->load('getFiscalWebhookSyncProcessorService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'];
        }
        $e = ($container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'] ?? $container->load('getFiscalStatusPollProcessorService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'];
        }

        $instance = new \App\Service\Fiscal\FiscalJobDispatcher($a, $b, $c, $d, $e, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'];
        }

        return $container->privates['App\\Service\\Fiscal\\FiscalJobDispatcher'] = $instance;
    }
}
