<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalSecretRedactorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Observability\FiscalSecretRedactor' shared autowired service.
     *
     * @return \App\Service\Fiscal\Observability\FiscalSecretRedactor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Observability'.\DIRECTORY_SEPARATOR.'FiscalSecretRedactor.php';

        return $container->privates['App\\Service\\Fiscal\\Observability\\FiscalSecretRedactor'] = new \App\Service\Fiscal\Observability\FiscalSecretRedactor();
    }
}
