<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalDashboardControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\FiscalDashboardController' autowired service.
     *
     * @return \App\Controller\FiscalDashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FiscalDashboardController.php';

        $container->factories['App\\Controller\\FiscalDashboardController'] = function ($container) {
            return new \App\Controller\FiscalDashboardController();
        };

        return $container->factories['App\\Controller\\FiscalDashboardController']($container);
    }
}
