<?php

namespace ContainerSCQslcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStorageDriverFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Storage\StorageDriverFactory' shared autowired service.
     *
     * @return \App\Service\Fiscal\Storage\StorageDriverFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Storage'.\DIRECTORY_SEPARATOR.'StorageDriverFactory.php';

        return $container->privates['App\\Service\\Fiscal\\Storage\\StorageDriverFactory'] = new \App\Service\Fiscal\Storage\StorageDriverFactory($container->getEnv('default::FISCAL_STORAGE_DRIVER'), (\dirname(__DIR__, 4).'/var/fiscal_storage'), 'http://localhost:8000/fiscal-files', $container->getEnv('default::FISCAL_S3_REGION'), $container->getEnv('default::FISCAL_S3_ENDPOINT'), $container->getEnv('default::FISCAL_S3_BUCKET'), $container->getEnv('default::FISCAL_S3_ACCESS_KEY'), $container->getEnv('default::FISCAL_S3_SECRET_KEY'), $container->getEnv('default::FISCAL_S3_PUBLIC_URL'), $container->getEnv('default::FISCAL_S3_KEY_PREFIX'));
    }
}
