<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSCQslcn\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSCQslcn/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSCQslcn.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSCQslcn\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerSCQslcn\App_KernelTestDebugContainer([
    'container.build_hash' => 'SCQslcn',
    'container.build_id' => 'c0515eea',
    'container.build_time' => 1780203421,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSCQslcn');
