<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxOJIOl\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxOJIOl/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerIxOJIOl.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerIxOJIOl\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerIxOJIOl\App_KernelTestDebugContainer([
    'container.build_hash' => 'IxOJIOl',
    'container.build_id' => '2cda421f',
    'container.build_time' => 1773280807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxOJIOl');
