<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJm3YUER\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJm3YUER/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJm3YUER.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJm3YUER\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJm3YUER\App_KernelTestDebugContainer([
    'container.build_hash' => 'Jm3YUER',
    'container.build_id' => '4910b4c8',
    'container.build_time' => 1780170745,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJm3YUER');
