<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Greenter\Api' shared autowired service.
     *
     * @return \Greenter\Api
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'lite'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Greenter'.\DIRECTORY_SEPARATOR.'Api.php';

        $container->services['Greenter\\Api'] = $instance = new \Greenter\Api(['auth' => $container->getEnv('AUTH_URL'), 'cpe' => $container->getEnv('API_URL')]);

        $instance->setBuilderOptions(['cache' => $container->targetDir.'']);

        return $instance;
    }
}
