<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigProviderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\ConfigProviderInterface' shared autowired service.
     *
     * @return \App\Service\FileConfigProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ConfigProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FileConfigProvider.php';

        return $container->services['App\\Service\\ConfigProviderInterface'] = new \App\Service\FileConfigProvider((\dirname(__DIR__, 4).'/data'), ($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')));
    }
}
