<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalConcurrentLoadCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\FiscalConcurrentLoadCommand' shared autowired service.
     *
     * @return \App\Command\FiscalConcurrentLoadCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'FiscalConcurrentLoadCommand.php';

        $container->privates['App\\Command\\FiscalConcurrentLoadCommand'] = $instance = new \App\Command\FiscalConcurrentLoadCommand(($container->privates['App\\Service\\Fiscal\\FiscalDocumentService'] ?? $container->load('getFiscalDocumentServiceService')));

        $instance->setName('app:fiscal:load-test');

        return $instance;
    }
}
