<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalCompanySyncServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalCompanySyncService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalCompanySyncService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalCompanySyncService.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalCompanySyncService'] = new \App\Service\Fiscal\FiscalCompanySyncService(($container->privates['App\\Service\\EmpresasService'] ?? $container->load('getEmpresasServiceService')), ($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'] ?? $container->load('getFiscalAuditServiceService')));
    }
}
