<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalFilesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FiscalFilesController' shared autowired service.
     *
     * @return \App\Controller\FiscalFilesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FiscalFilesController.php';

        return $container->services['App\\Controller\\FiscalFilesController'] = new \App\Controller\FiscalFilesController((\dirname(__DIR__, 4).'/var/fiscal_storage'));
    }
}
