<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalConnectionTestServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalConnectionTestService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalConnectionTestService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalConnectionTestService.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalConnectionTestService'] = new \App\Service\Fiscal\FiscalConnectionTestService(($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->privates['App\\Service\\Fiscal\\Provider\\FiscalProviderResolver'] ?? $container->load('getFiscalProviderResolverService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\Fiscal\\FiscalCompanySyncService'] ?? $container->load('getFiscalCompanySyncServiceService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'] ?? $container->load('getFiscalAuditServiceService')));
    }
}
