<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalQueueServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalQueueService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalQueueService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalQueueService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalJobDispatcher.php';

        $instance = new \App\Service\Fiscal\FiscalQueueService($container->getEnv('default::REDIS_URL'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalQueueService'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalQueueService'];
        }

        $container->privates['App\\Service\\Fiscal\\FiscalQueueService'] = $instance;

        $instance->setJobDispatcher(new \App\Service\Fiscal\FiscalJobDispatcher($instance, ($container->privates['App\\Service\\Fiscal\\FiscalEmitProcessor'] ?? $container->load('getFiscalEmitProcessorService')), ($container->privates['App\\Service\\Fiscal\\FiscalEmailProcessor'] ?? $container->load('getFiscalEmailProcessorService')), ($container->privates['App\\Service\\Fiscal\\FiscalWebhookSyncProcessor'] ?? $container->load('getFiscalWebhookSyncProcessorService')), ($container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'] ?? $container->load('getFiscalStatusPollProcessorService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))));

        return $instance;
    }
}
