<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerceptionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\v1\PerceptionController' autowired service.
     *
     * @return \App\Controller\v1\PerceptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'v1'.\DIRECTORY_SEPARATOR.'PerceptionController.php';

        $container->factories['App\\Controller\\v1\\PerceptionController'] = function ($container) {
            $instance = new \App\Controller\v1\PerceptionController(($container->privates['App\\Service\\DocumentRequest'] ?? $container->load('getDocumentRequestService')));

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Controller\\v1\\PerceptionController'] ?? $container->load('getPerceptionController2Service')));

            return $instance;
        };

        return $container->factories['App\\Controller\\v1\\PerceptionController']($container);
    }
}
