<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfReportDecoratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\PdfReportDecorator' shared autowired service.
     *
     * @return \App\Service\PdfReportDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'ReportInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PdfReportDecorator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HtmlReportDecorator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'HtmlReport.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'TemplateResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'DefaultTemplateResolver.php';

        return $container->services['App\\Service\\PdfReportDecorator'] = new \App\Service\PdfReportDecorator(new \App\Service\HtmlReportDecorator(new \Greenter\Report\HtmlReport($container->getEnv('default::TEMPLATESPDF_PATH'), ['cache' => $container->targetDir.'', 'strict_variables' => true]), ($container->services['Greenter\\Report\\Resolver\\TemplateResolverInterface'] ??= new \Greenter\Report\Resolver\DefaultTemplateResolver())), $container->getEnv('WKHTMLTOPDF_PATH'), ['no-outline', 'print-media-type'], \dirname(__DIR__, 4));
    }
}
