<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'serializer' shared autowired service.
     *
     * @return \App\Adapter\SerializerAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'SerializerAdapter.php';

        return $container->services['serializer'] = new \App\Adapter\SerializerAdapter(($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')));
    }
}
