<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeeApiFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\SeeApiFactory' shared autowired service.
     *
     * @return \App\Service\SeeApiFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SeeApiFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ConfigProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EnvConfigProvider.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FileDataReader.php';

        return $container->services['App\\Service\\SeeApiFactory'] = new \App\Service\SeeApiFactory(($container->privates['App\\Service\\EnvConfigProvider'] ??= new \App\Service\EnvConfigProvider()), ($container->services['App\\Service\\ConfigProviderInterface'] ?? $container->load('getConfigProviderInterfaceService')), ($container->services['App\\Service\\FileDataReader'] ??= new \App\Service\FileDataReader((\dirname(__DIR__, 4).'/data'))), ($container->services['Greenter\\Api'] ?? $container->load('getApiService')));
    }
}
