<?php

namespace ContainerLtInaTh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoidedControllerstatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CkeVmBk.App\Controller\v1\VoidedController::status()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CkeVmBk.App\\Controller\\v1\\VoidedController::status()'] = ($container->privates['.service_locator.CkeVmBk'] ?? $container->load('get_ServiceLocator_CkeVmBkService'))->withContext('App\\Controller\\v1\\VoidedController::status()', $container);
    }
}
