<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_ContainerRepositoryFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.container_repository_factory' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'orm'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RepositoryFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'doctrine-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RepositoryFactoryCompatibility.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'doctrine-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ContainerRepositoryFactory.php';

        return $container->privates['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Repository\\AdminUserRepository' => ['privates', 'App\\Repository\\AdminUserRepository', 'getAdminUserRepositoryService', true],
            'App\\Repository\\EmpresaRepository' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
            'App\\Repository\\FiscalAlertRepository' => ['privates', 'App\\Repository\\FiscalAlertRepository', 'getFiscalAlertRepositoryService', true],
            'App\\Repository\\FiscalAuditLogRepository' => ['privates', 'App\\Repository\\FiscalAuditLogRepository', 'getFiscalAuditLogRepositoryService', true],
            'App\\Repository\\FiscalDocumentRepository' => ['privates', 'App\\Repository\\FiscalDocumentRepository', 'getFiscalDocumentRepositoryService', true],
            'App\\Repository\\FiscalEmitAttemptRepository' => ['privates', 'App\\Repository\\FiscalEmitAttemptRepository', 'getFiscalEmitAttemptRepositoryService', true],
            'App\\Repository\\FiscalTenantMetricRepository' => ['privates', 'App\\Repository\\FiscalTenantMetricRepository', 'getFiscalTenantMetricRepositoryService', true],
            'App\\Repository\\FiscalWebhookEventRepository' => ['privates', 'App\\Repository\\FiscalWebhookEventRepository', 'getFiscalWebhookEventRepositoryService', true],
            'App\\Repository\\OutboundEmailLogRepository' => ['privates', 'App\\Repository\\OutboundEmailLogRepository', 'getOutboundEmailLogRepositoryService', true],
        ], [
            'App\\Repository\\AdminUserRepository' => '?',
            'App\\Repository\\EmpresaRepository' => '?',
            'App\\Repository\\FiscalAlertRepository' => '?',
            'App\\Repository\\FiscalAuditLogRepository' => '?',
            'App\\Repository\\FiscalDocumentRepository' => '?',
            'App\\Repository\\FiscalEmitAttemptRepository' => '?',
            'App\\Repository\\FiscalTenantMetricRepository' => '?',
            'App\\Repository\\FiscalWebhookEventRepository' => '?',
            'App\\Repository\\OutboundEmailLogRepository' => '?',
        ]));
    }
}
