<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresasServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\EmpresasService' shared autowired service.
     *
     * @return \App\Service\EmpresasService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmpresasService.php';

        return $container->privates['App\\Service\\EmpresasService'] = new \App\Service\EmpresasService(($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), (\dirname(__DIR__, 4).'/data'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
