<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalStatusPollProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalStatusPollProcessor' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalStatusPollProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalStatusPollProcessor.php';

        $a = ($container->privates['App\\Service\\Fiscal\\FiscalQueueService'] ?? $container->load('getFiscalQueueServiceService'));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'];
        }

        $instance = new \App\Service\Fiscal\FiscalStatusPollProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\FiscalDocumentRepository'] ?? $container->load('getFiscalDocumentRepositoryService')), ($container->privates['App\\Repository\\EmpresaRepository'] ?? $container->load('getEmpresaRepositoryService')), ($container->services['serializer'] ?? $container->load('getSerializerService')), ($container->privates['App\\Service\\Fiscal\\FiscalStorageService'] ?? $container->load('getFiscalStorageServiceService')), ($container->privates['App\\Service\\Fiscal\\FiscalWebhookService'] ?? $container->load('getFiscalWebhookServiceService')), $a, ($container->services['App\\Service\\SeeFactory'] ?? $container->load('getSeeFactoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['App\\Service\\Fiscal\\FiscalDocumentPdfResolver'] ?? $container->load('getFiscalDocumentPdfResolverService')));

        if (isset($container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'])) {
            return $container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'];
        }

        return $container->privates['App\\Service\\Fiscal\\FiscalStatusPollProcessor'] = $instance;
    }
}
