<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalOperationsControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\v1\FiscalOperationsController' autowired service.
     *
     * @return \App\Controller\v1\FiscalOperationsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'v1'.\DIRECTORY_SEPARATOR.'FiscalOperationsController.php';

        $container->factories['App\\Controller\\v1\\FiscalOperationsController'] = function ($container) {
            $instance = new \App\Controller\v1\FiscalOperationsController(($container->privates['App\\Service\\Fiscal\\Observability\\FiscalHealthService'] ?? $container->load('getFiscalHealthServiceService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalOperationsService'] ?? $container->load('getFiscalOperationsServiceService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAlertService'] ?? $container->load('getFiscalAlertServiceService')), ($container->privates['App\\Service\\Fiscal\\Observability\\FiscalAuditService'] ?? $container->load('getFiscalAuditServiceService')));

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Controller\\v1\\FiscalOperationsController'] ?? $container->load('getFiscalOperationsController2Service')));

            return $instance;
        };

        return $container->factories['App\\Controller\\v1\\FiscalOperationsController']($container);
    }
}
