<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalPdfServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\FiscalPdfService' shared autowired service.
     *
     * @return \App\Service\Fiscal\FiscalPdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'FiscalPdfService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FileDataReader.php';

        return $container->privates['App\\Service\\Fiscal\\FiscalPdfService'] = new \App\Service\Fiscal\FiscalPdfService(($container->services['App\\Service\\PdfReportDecorator'] ?? $container->load('getPdfReportDecoratorService')), ($container->services['App\\Service\\SeeFactory'] ?? $container->load('getSeeFactoryService')), ($container->services['App\\Service\\ConfigProviderInterface'] ?? $container->load('getConfigProviderInterfaceService')), ($container->services['App\\Service\\FileDataReader'] ??= new \App\Service\FileDataReader((\dirname(__DIR__, 4).'/data'))), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
