<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalStressTestCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\FiscalStressTestCommand' shared autowired service.
     *
     * @return \App\Command\FiscalStressTestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'FiscalStressTestCommand.php';

        $container->privates['App\\Command\\FiscalStressTestCommand'] = $instance = new \App\Command\FiscalStressTestCommand(($container->privates['App\\Service\\Fiscal\\FiscalDocumentService'] ?? $container->load('getFiscalDocumentServiceService')));

        $instance->setName('app:fiscal:stress-test');

        return $instance;
    }
}
