<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiscalEmpresasControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\FiscalEmpresasController' autowired service.
     *
     * @return \App\Controller\FiscalEmpresasController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FiscalEmpresasController.php';

        $container->factories['App\\Controller\\FiscalEmpresasController'] = function ($container) {
            return new \App\Controller\FiscalEmpresasController();
        };

        return $container->factories['App\\Controller\\FiscalEmpresasController']($container);
    }
}
