<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlReportDecoratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\HtmlReportDecorator' shared autowired service.
     *
     * @return \App\Service\HtmlReportDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'ReportInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HtmlReportDecorator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'HtmlReport.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'TemplateResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'DefaultTemplateResolver.php';

        return $container->privates['App\\Service\\HtmlReportDecorator'] = new \App\Service\HtmlReportDecorator(($container->privates['Greenter\\Report\\HtmlReport'] ??= new \Greenter\Report\HtmlReport($container->getEnv('default::TEMPLATESPDF_PATH'), ['cache' => $container->targetDir.'', 'strict_variables' => true])), ($container->services['Greenter\\Report\\Resolver\\TemplateResolverInterface'] ??= new \Greenter\Report\Resolver\DefaultTemplateResolver()));
    }
}
