<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_IdenticalPropertyNamingStrategyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.identical_property_naming_strategy' shared service.
     *
     * @return \JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'jms'.\DIRECTORY_SEPARATOR.'serializer'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Naming'.\DIRECTORY_SEPARATOR.'PropertyNamingStrategyInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'jms'.\DIRECTORY_SEPARATOR.'serializer'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Naming'.\DIRECTORY_SEPARATOR.'IdenticalPropertyNamingStrategy.php';

        return $container->privates['jms_serializer.identical_property_naming_strategy'] = new \JMS\Serializer\Naming\IdenticalPropertyNamingStrategy();
    }
}
