<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPseAuthBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Fiscal\Provider\PseAuthBuilder' shared autowired service.
     *
     * @return \App\Service\Fiscal\Provider\PseAuthBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fiscal'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'PseAuthBuilder.php';

        return $container->privates['App\\Service\\Fiscal\\Provider\\PseAuthBuilder'] = new \App\Service\Fiscal\Provider\PseAuthBuilder();
    }
}
