<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrRenderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Greenter\Report\Render\QrRender' shared autowired service.
     *
     * @return \Greenter\Report\Render\QrRender
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Render'.\DIRECTORY_SEPARATOR.'QrRender.php';

        return $container->privates['Greenter\\Report\\Render\\QrRender'] = new \Greenter\Report\Render\QrRender();
    }
}
