<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_Loader_Attribute_ServicesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'routing.loader.attribute.services' shared service.
     *
     * @return \Symfony\Component\Routing\Loader\AttributeServicesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'config'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'LoaderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'config'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'Loader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'routing'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'AttributeServicesLoader.php';

        return $container->privates['routing.loader.attribute.services'] = new \Symfony\Component\Routing\Loader\AttributeServicesLoader(['App\\Controller\\AccountController', 'App\\Controller\\FiscalDashboardController', 'App\\Controller\\FiscalEmpresasController', 'App\\Controller\\FiscalFilesController', 'App\\Controller\\HomeController', 'App\\Controller\\SecurityController', 'App\\Controller\\v1\\ConfigurationController', 'App\\Controller\\v1\\DespatchController', 'App\\Controller\\v1\\EmpresasController', 'App\\Controller\\v1\\FiscalController', 'App\\Controller\\v1\\FiscalOperationsController', 'App\\Controller\\v1\\InvoiceController', 'App\\Controller\\v1\\NoteController', 'App\\Controller\\v1\\PerceptionController', 'App\\Controller\\v1\\RetentionController', 'App\\Controller\\v1\\ReversionController', 'App\\Controller\\v1\\SaleController', 'App\\Controller\\v1\\SummaryController', 'App\\Controller\\v1\\VoidedController']);
    }
}
