<?php

namespace ContainerPgz4uqu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaleControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\v1\SaleController' autowired service.
     *
     * @return \App\Controller\v1\SaleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'v1'.\DIRECTORY_SEPARATOR.'SaleController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'greenter'.\DIRECTORY_SEPARATOR.'report'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'Render'.\DIRECTORY_SEPARATOR.'QrRender.php';

        $container->factories['App\\Controller\\v1\\SaleController'] = function ($container) {
            $instance = new \App\Controller\v1\SaleController(($container->privates['Greenter\\Report\\Render\\QrRender'] ??= new \Greenter\Report\Render\QrRender()));

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Controller\\v1\\SaleController'] ?? $container->load('getSaleController2Service')));

            return $instance;
        };

        return $container->factories['App\\Controller\\v1\\SaleController']($container);
    }
}
