<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGzcUNgA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGzcUNgA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGzcUNgA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGzcUNgA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGzcUNgA\App_KernelDevDebugContainer([
    'container.build_hash' => 'GzcUNgA',
    'container.build_id' => '77755e23',
    'container.build_time' => 1779606821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGzcUNgA');
