<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB6HuHsX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB6HuHsX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB6HuHsX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB6HuHsX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB6HuHsX\App_KernelDevDebugContainer([
    'container.build_hash' => 'B6HuHsX',
    'container.build_id' => '4b2b5e56',
    'container.build_time' => 1779947463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB6HuHsX');
