<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkjyALH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkjyALH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOkjyALH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOkjyALH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOkjyALH\App_KernelDevDebugContainer([
    'container.build_hash' => 'OkjyALH',
    'container.build_id' => 'a15a5c00',
    'container.build_time' => 1780203326,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkjyALH');
